name: CI-CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # 允許手動觸發

jobs:
  detect-changes:
    runs-on: self-hosted # Windows 自託管 Runner
    outputs:
      apigateway: ${{ steps.set-outputs.outputs.apigateway }}
      biglist: ${{ steps.set-outputs.outputs.biglist }}
      sharemodel: ${{ steps.set-outputs.outputs.sharemodel }}
      usermanagement: ${{ steps.set-outputs.outputs.usermanagement }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 獲取當前和前一個提交以比較變動

      - name: Detect changed services
        id: set-outputs
        shell: powershell
        run: |
          # 檢查變動檔案
          git diff --name-only HEAD^ HEAD | Out-File -FilePath changed_files.txt -Encoding utf8
          Write-Host "Changed files:"
          Get-Content changed_files.txt

          # 初始化輸出
          $apigateway = "false"
          $biglist = "false"
          $usermanagement = "false"
          $sharemodel = "false"

          # 若 ShareModel 有變動，則所有服務都需要重新建置
          if (Select-String -Path changed_files.txt -Pattern "^SharedModels/" -Quiet) {
            $apigateway = "true"
            $biglist = "true"
            $usermanagement = "true"
            $sharemodel = "true"
          } else {
            # 檢測 ApiGateway 是否有變動
            if (Select-String -Path changed_files.txt -Pattern "^ApiGateway/" -Quiet) {
              $apigateway = "true"
            }
            # 檢測 BigList 是否有變動
            if (Select-String -Path changed_files.txt -Pattern "^BigList/" -Quiet) {
              $biglist = "true"
            }
            # 檢測 UserManagementMicroservice 是否有變動
            if (Select-String -Path changed_files.txt -Pattern "^UserManagementMicroservice/" -Quiet) {
              $usermanagement = "true"
            }
          }

          # 將輸出寫入 GITHUB_OUTPUT
          "apigateway=$apigateway" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "biglist=$biglist" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "usermanagement=$usermanagement" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          "sharemodel=$sharemodel" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

  build-and-deploy-apigateway:
    needs: detect-changes
    if: needs.detect-changes.outputs.apigateway == 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ApiGateway/ApiGateway.csproj

      - name: Build
        run: dotnet build ApiGateway/ApiGateway.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ApiGateway/ApiGateway.csproj --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish ApiGateway/ApiGateway.csproj --configuration Release --output ./publish/ApiGateway

      - name: Deploy to IIS
        run: |
          Stop-WebSite -Name "Gateway" -ErrorAction SilentlyContinue
          Remove-Item -Path "C:\inetpub\wwwroot\ApiGateway\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "./publish/ApiGateway/*" -Destination "C:\inetpub\wwwroot\ApiGateway" -Recurse -Force
          Start-WebSite -Name "Gateway"
        shell: powershell

  build-and-deploy-biglist:
    needs: detect-changes
    if: needs.detect-changes.outputs.biglist == 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BigList/BigList.csproj

      - name: Build
        run: dotnet build BigList/BigList.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test BigList/BigList.csproj --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish BigList/BigList.csproj --configuration Release --output ./publish/BigList

      - name: Deploy to IIS
        run: |
          Stop-WebSite -Name "TestBugList" -ErrorAction SilentlyContinue
          Remove-Item -Path "C:\inetpub\wwwroot\TestBugList\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "./publish/BigList/*" -Destination "C:\inetpub\wwwroot\TestBugList" -Recurse -Force
          Start-WebSite -Name "TestBugList"
        shell: powershell

  build-and-deploy-usermanagement:
    needs: detect-changes
    if: needs.detect-changes.outputs.usermanagement == 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore UserManagementMicroservice/UserManagementMicroservice.csproj

      - name: Build
        run: dotnet build UserManagementMicroservice/UserManagementMicroservice.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test UserManagementMicroservice/UserManagementMicroservice.csproj --no-build --verbosity normal
        continue-on-error: true

      - name: Publish
        run: dotnet publish UserManagementMicroservice/UserManagementMicroservice.csproj --configuration Release --output ./publish/UserManagementMicroservice

      - name: Deploy to IIS
        run: |
          Stop-WebSite -Name "Test" -ErrorAction SilentlyContinue
          Remove-Item -Path "C:\inetpub\wwwroot\Test\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Path "./publish/UserManagementMicroservice/*" -Destination "C:\inetpub\wwwroot\Test" -Recurse -Force
          Start-WebSite -Name "Test"
        shell: powershell